# Generated by Django 6.0.3 on 2026-04-17 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0002_alter_trip_slug'),
        ('waypoints', '0002_alter_waypoint_latitude_alter_waypoint_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/%Y/%m/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='photos/thumb/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('is_thumbnail_generated', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='trips.trip')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL)),
                ('waypoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='waypoints.waypoint')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
