# Generated by Django 6.0.3 on 2026-04-19 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-uploaded_at'], 'permissions': [('can_moderate_photos', 'Can delete any photo')]},
        ),
    ]
