# Generated by Django 6.0.3 on 2026-04-16 18:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0002_alter_trip_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaypointCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, help_text='CSS icon class, e.g. bi-fuel-pump (for future Leaflet markers)', max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Waypoint Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('elevation', models.IntegerField(blank=True, help_text='Elevation in meters', null=True)),
                ('order', models.PositiveIntegerField(help_text='Display order within the trip')),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='trips.trip')),
                ('categories', models.ManyToManyField(blank=True, related_name='waypoints', to='waypoints.waypointcategory')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('trip', 'order')},
            },
        ),
    ]
