# Generated by Django 6.0.3 on 2026-04-02 19:39

from django.db import migrations


def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group') # noqa: N806
    Group.objects.get_or_create(name='Rider')
    Group.objects.get_or_create(name='Moderator')


def remove_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group') # noqa: N806
    Group.objects.filter(name__in=['Rider', 'Moderator']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups, remove_groups),
    ]
