# Generated by Django 6.0.3 on 2026-04-19 12:39

from django.db import migrations



def assign_permissions(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    moderator_permissions = [
        'can_moderate_trail_notes',
        'can_feature_trips',
    ]

    try:
        moderator_group = Group.objects.get(name='Moderator')
    except Group.DoesNotExist:
        return

    for codename in moderator_permissions:
        try:
            perm = Permission.objects.get(codename=codename)
            moderator_group.permissions.add(perm)
        except Permission.DoesNotExist:
            pass


def remove_permissions(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    try:
        moderator_group = Group.objects.get(name='Moderator')
        moderator_group.permissions.clear()
    except Group.DoesNotExist:
        pass



class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_seed_groups'),
        ('community', '0001_initial'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(assign_permissions, remove_permissions),
    ]
