# Generated by Django 6.0.3 on 2026-04-19 14:18

from django.db import migrations


def add_permission(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    try:
        mod = Group.objects.get(name='Moderator')
        perm = Permission.objects.get(codename='can_moderate_photos')
        mod.permissions.add(perm)
    except (Group.DoesNotExist, Permission.DoesNotExist):
        pass


def remove_permission(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    try:
        mod = Group.objects.get(name='Moderator')
        perm = Permission.objects.get(codename='can_moderate_photos')
        mod.permissions.remove(perm)
    except (Group.DoesNotExist, Permission.DoesNotExist):
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_assign_moderator_permissions'),
        ('gallery', '0002_alter_photo_options'),
    ]

    operations = [
        migrations.RunPython(add_permission, remove_permission),
    ]